package com.blucharge.ocpp.enums;

public enum ChargePointErrorCode {
    CONNECTOR_LOCK_FAILURE,
    EV_COMMUNICATION_ERROR,
    GROUND_FAILURE,
    HIGH_TEMPERATURE,
    INTERNAL_ERROR,
    LOCAL_LIST_CONFLICT,
    NO_ERROR,
    OTHER_ERROR,
    OVER_CURRENT_FAILURE,
    OVER_VOLTAGE,
    POWER_METER_FAILURE,
    POWER_SWITCH_FAILURE,
    READER_FAILURE,
    RESET_FAILURE,
    UNDER_VOLTAGE,
    WEAK_SIGNAL,
    EXT_URGENT_BTN_DOWN
}


